#name: ✔ Flutter Release
#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master
#
#jobs:
#  build_android_mobile:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v2
#        with:
#          distribution: "zulu"
#          java-version: "11.*"
#      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.7.10'
#          channel: 'stable'
#          cache: true
#          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
#          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
##          architecture: arm64 # optional, x64 or arm64
#      - run: flutter --version
#      - run: flutter pub get
#      - run: flutter build apk
#      - run: flutter build appbundle