name: ✔ Flutter Release
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_android_mobile:
    runs-on: self-hosted
    steps:
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
      - run: echo hi > world.txt
      - name: 📦 Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build/app/outputs/apk/release/app-release.apk
      - name: 📦 Upload AppBundle artifact
        uses: actions/upload-artifact@v3
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab