name: ✔ Flutter Release
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_android_mobile:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./
    steps:
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
      - name: 📦 Upload apk artifact
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: build/app/outputs/apk/release/app-release.apk
      - name: 📦 Upload appbundle artifact
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab