name: ✔ Flutter Release
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_android_mobile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.10'
          channel: 'stable'
      - run: flutter --version